import type { PlantingAdvice } from "@/lib/gemini";

const RISK_STYLES: Record<PlantingAdvice["riskLevel"], string> = {
  low: "bg-emerald-100 text-emerald-800 dark:bg-emerald-900/40 dark:text-emerald-300",
  medium: "bg-amber-100 text-amber-800 dark:bg-amber-900/40 dark:text-amber-300",
  high: "bg-red-100 text-red-800 dark:bg-red-900/40 dark:text-red-300",
};

export default function PlantingAdviceCard({ advice }: { advice: PlantingAdvice }) {
  return (
    <div className="rounded-xl border border-zinc-200 bg-white p-4 dark:border-zinc-800 dark:bg-zinc-900">
      <div className="flex items-center justify-between">
        <h3 className="text-sm font-semibold text-zinc-900 dark:text-zinc-100">
          Planting recommendation
        </h3>
        <span
          className={`rounded-full px-2.5 py-0.5 text-xs font-medium ${RISK_STYLES[advice.riskLevel]}`}
        >
          {advice.riskLevel} risk
        </span>
      </div>

      <dl className="mt-3 space-y-2 text-sm">
        <div>
          <dt className="text-xs font-medium text-zinc-500">Planting window</dt>
          <dd className="text-zinc-900 dark:text-zinc-100">{advice.plantingWindow}</dd>
        </div>
        <div>
          <dt className="text-xs font-medium text-zinc-500">Estimated harvest window</dt>
          <dd className="text-zinc-900 dark:text-zinc-100">
            {advice.estimatedHarvestWindow}
          </dd>
        </div>
        <div>
          <dt className="text-xs font-medium text-zinc-500">Why</dt>
          <dd className="text-zinc-700 dark:text-zinc-300">{advice.reasoning}</dd>
        </div>
      </dl>

      <div className="mt-3">
        <p className="text-xs font-medium text-zinc-500">What to do</p>
        <ul className="mt-1 list-disc space-y-1 pl-5 text-sm text-zinc-700 dark:text-zinc-300">
          {advice.actionItems.map((item, i) => (
            <li key={i}>{item}</li>
          ))}
        </ul>
      </div>

      <p className="mt-3 text-[11px] text-zinc-400">
        Generated by Gemini from BMKG data — always confirm with your local extension
        officer for major decisions.
      </p>
    </div>
  );
}
